name: Update Version Numbers

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  update-versions:
    # Only run if the PR was merged AND it's not a version update PR
    if: |
      github.event.pull_request.merged == true && 
      !startsWith(github.event.pull_request.title, 'Update version numbers')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Create new branch for version update
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create a new branch for version updates
          VERSION_BRANCH="version-update-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $VERSION_BRANCH
          echo "VERSION_BRANCH=$VERSION_BRANCH" >> $GITHUB_ENV
      
      - name: Update version numbers
        id: update_versions
        run: |
          # Show original file content for debugging
          echo "Original index.html version strings:"
          grep -E '(href="|src="|CHORES_APP_VERSION).*\?v=' custom_components/chores_manager/www/chores-dashboard/index.html || echo "No version strings found"
          
          echo "Original panel.py version string:"
          grep -E 'js_url=' custom_components/chores_manager/panel.py || echo "No version string found"
          
          # Create the Python script
          cat > update_versions.py << 'EOF'
          #!/usr/bin/env python3
          import os
          import re
          import datetime
          import subprocess
          from pathlib import Path

          # Get current date in YYYYMMDD format
          today = datetime.datetime.now().strftime('%Y%m%d')

          # Get short commit hash 
          short_hash = subprocess.check_output(['git', 'rev-parse', '--short', 'HEAD']).decode('utf-8').strip()

          # Version string to use (date + commit hash + random)
          import random
          random_suffix = f"{random.randint(1000, 9999)}"
          version_string = f"{today}-{short_hash}-{random_suffix}"
          print(f"Using version string: {version_string}")

          # Files to update and their patterns
          FILES_TO_UPDATE = [
              {
                  'path': 'custom_components/chores_manager/www/chores-dashboard/index.html',
                  'patterns': [
                      # Use full version string for all cache busting parameters
                      (r'(href="[^"]+\?v=)[^"]+(")', f'\\1{version_string}\\2'),
                      (r'(src="[^"]+\?v=)[^"]+(")', f'\\1{version_string}\\2'),
                      (r'(CHORES_APP_VERSION = "[^"]+-)[^"]+"', f'\\1{version_string}"')
                  ]
              },
              {
                  'path': 'custom_components/chores_manager/panel.py',
                  'patterns': [
                      # Use full version string here too
                      (r'(js_url="/local/chores-dashboard/chores-dashboard.js\?v=)[^"]+(")', f'\\1{version_string}\\2')
                  ]
              }
          ]

          def update_file(file_path, patterns):
              path = Path(file_path)
              if not path.exists():
                  print(f"File not found: {file_path}")
                  return False
                  
              content = path.read_text()
              original_content = content
              
              for pattern, replacement in patterns:
                  print(f"Applying pattern: {pattern}")
                  # Print matched substrings for debugging
                  import re
                  matches = re.findall(pattern, content)
                  print(f"  Found {len(matches)} matches: {matches[:3]}")
                  
                  content = re.sub(pattern, replacement, content)
              
              if content != original_content:
                  # Show the differences
                  for i, (orig_line, new_line) in enumerate(zip(original_content.splitlines(), content.splitlines())):
                      if orig_line != new_line:
                          print(f"Line {i+1} changed from: {orig_line}")
                          print(f"Line {i+1} changed to:   {new_line}")
                  
                  path.write_text(content)
                  print(f"Updated: {file_path}")
                  return True
              
              print(f"No changes needed: {file_path}")
              return False

          def main():
              updated = False
              
              for file_info in FILES_TO_UPDATE:
                  file_updated = update_file(file_info['path'], file_info['patterns'])
                  updated = updated or file_updated
              
              if updated:
                  print(f"Version numbers updated to {version_string}")
                  # Create a file to signal success
                  with open("version_updated.txt", "w") as f:
                      f.write(f"Version updated to {version_string}")
                  return 0
              else:
                  print("No version numbers needed updating")
                  return 1

          if __name__ == "__main__":
              exit(main())
          EOF
          
          # Execute the script
          python update_versions.py
          
          # Check if updates were made
          if [ -f "version_updated.txt" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            cat version_updated.txt
            
            # Show updated content for debugging
            echo "Updated index.html version strings:"
            grep -E '(href="|src="|CHORES_APP_VERSION).*\?v=' custom_components/chores_manager/www/chores-dashboard/index.html
            
            echo "Updated panel.py version string:"
            grep -E 'js_url=' custom_components/chores_manager/panel.py
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes were made to version numbers"
          fi

      - name: Commit changes and push branch
        if: steps.update_versions.outputs.changes == 'true'
        run: |
          # Make sure there are actual git differences
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Git detects changes, committing and pushing..."
            git add .
            git commit -m "Update version numbers [skip ci]"
            git push --set-upstream origin ${{ env.VERSION_BRANCH }}
            echo "Changes pushed to branch ${{ env.VERSION_BRANCH }}"
          else
            echo "Git reports no changes despite script reporting changes"
            exit 1
          fi

      - name: Create Pull Request
        if: steps.update_versions.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update version numbers"
          body: |
            This PR updates version numbers in the application files for better cache busting.
            
            - Updates CSS and JS version parameters
            - Updates app version variable
            
            This PR was automatically created after a successful merge to ensure all version numbers are up to date.
          branch: ${{ env.VERSION_BRANCH }}
          base: main
          delete-branch: false  # Keep the branch even if it appears identical